#!/bin/csh
# Lectures
# Print side-by-side for packet
# chap24-25 examples of RPC programs: dropped
foreach topic ( homework01 homework02 homework03 homework04 homework05 homework06 homework07 homework08 homework09 homework10 homework11 homework12 homework13 homework14 homework15 homework16 homework17 homework18 homework19 homework20 homework21 homework22 homework23 homework24  )
#  pic -c {$topic}.pic > {$topic}.tex
  tex  {$topic}.tex
  dvipdf {$topic}.dvi 
#  psnup -2 -d -pletter {$topic}.ps | lpr -h -Pecsprinter
  rm {$topic}.log {$topic}.dvi
#  sleep 10
  mv {$topic}.pdf ./pdfs/
end
