#!/bin/csh
# Lectures
# Print side-by-side for packet
# chap24-25 examples of RPC programs: dropped
foreach topic ( intro unix chap01 chap02 chap03 chap04 chap05 chap06 chap07 chap08 chap09 chap10 chap11 chap12 chap13 chap13b chap14 chap15 broadcast multicast chap16 chap17 chap18 chap19 chap20 chap21 chap22-23 chap30 advanced_sockets corba ssl ipv6 review )
  pic -c {$topic}.pic > {$topic}.tex
  tex  {$topic}.tex
  dvips -f < {$topic}.dvi -o {$topic}.ps
  psnup -2 -d -pletter {$topic}.ps | lpr -h -Pecsprinter
  rm {$topic}.tex {$topic}.log {$topic}.dvi {$topic}.ps
  sleep 10
end
